# Base image olaraq ən son Ubuntu istifadə et
FROM ubuntu:latest

# APT paketlərini yenilə və mövcud proqramları upgrade et
RUN apt-get update && apt-get upgrade -y

# Container işə düşəndə "Hello, World!" yazdır
CMD echo "Hello, World!"
