# Use the latest Ubuntu as the base image
FROM ubuntu:latest

# Update APT packages and upgrade existing software
RUN apt-get update && apt-get upgrade -y

# When the container starts, print "Hello, World!"
CMD echo "Hello, World!"